project:
  type: website

execute:
  freeze: auto # Re-render only when source changes

website:
  title: "Digital History Methods"
  page-navigation: true
  favicon: files/logo.png
  site-url: https://jessesadler.github.io/vt5444s26/
  repo-url: https://github.com/jessesadler/vt5444s26
  repo-actions: [edit,issue]

  announcement:
    icon: calendar-check
    dismissable: true
    content: "The syllabus is being constantly updated. Continue to check in for updates."
    type: primary
    position: below-navbar

  navbar:
    pinned: true
    background: "#E5751F"
    foreground: "#000000"
    right:
      - href: about.qmd
        text: "Course Details"
      - href: content/index.qmd
        text: Content
      - href: worksheets/index.qmd
        text: Worksheets
      - href: assignments.qmd
        text: Assignments
      - href: resources/index.qmd
        text: Resources
  
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Topics"
          contents:
            - text: "1: MLK Day - No class"
            - text: "2: History, data, and the digital"
              file: content/02-content-data-history.qmd
            - text: "3: The file system and Markdown"
              file: content/03-content-md.qmd
            - text: "4: 'Tidy' historical data"
              file: content/04-content-tidy.qmd
            - text: "5: Visualizing data with ggplot2"
              file: content/05-content-ggplot.qmd
            - text: "6: Wrangling data"
              file: content/06-content-dplyr.qmd
            - text: "7: Working with SNiGB"
              file: content/07-content-snigb.qmd
            - text: "8: Reproducible workflows with Git"
              file: content/08-content-git.qmd
            - text: "9: Making websites with Quarto"
              file: content/09-content-quarto.qmd
            - text: "10: Making maps"
              file: content/10-content-maps.qmd
            - text: "11: Network analysis"
              file: content/11-content-networks.qmd
            - text: "12: Web design and visualization"
              file: content/12-content-design.qmd
            - text: "13: Mapping and network analysis"
              file: content/13-content-gis-sna.qmd
            - text: "14: Group work on your project"
              file: content/14-content-build.qmd
            - text: "15: Presentation of final projects"
              file: content/15-content-presentations.qmd

    - title: "Worksheets"
      style: "docked"
      search: false
      contents:
        - section: "Overview"
          contents:
            - worksheets/index.qmd
        - section: "How to"
          contents:
            - text: "1: Getting started with R"
              file: worksheets/01-worksheet.qmd
    
    - title: "Resources"
      style: "docked"
      search: false
      contents:
        - section: "Overview"
          contents:
            - text: "Resources"
              file: resources/index.qmd
        - section: "Digital Humanities"
          contents:
            - text: "General DH resources"
              file: resources/dh.qmd
            - text: "Data for DH"
              file: resources/datasets.qmd
        - section: "Organization"
          contents:
            - text: "Zotero Guide"
              file: resources/zotero.qmd
            - text: "Working with Plain Text"
              file: resources/plaintext.qmd
            - text: "Markdown Syntax Guide"
              file: resources/markdown-syntax.qmd
            - text: "Text editors"
              file: resources/text-editors.qmd

  page-footer:
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/jessesadler/vt5444s26)
    left: "&copy; Copyright 2026, [Jesse Sadler](https://www.jessesadler.com)"

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: solar
    toc: true
  live-html:
    theme:
      light: [cosmo, custom.scss]
      dark: solar
    toc: true

