project:
  type: website

execute:
  freeze: auto # Re-render only when source changes

website:
  title: "Digital History Methods"

  announcement:
    icon: calendar-check
    dismissable: true
    content: "This is a **draft** version of the syllabus. The contents will change frequently."
    type: secondary
    position: below-navbar

  navbar:
    pinned: true
    background: "#ffaa00"
    right:
      - href: about.qmd
        text: "Course Details"
      - href: content/index.qmd
        text: Content
      - href: worksheets/index.qmd
        text: Worksheets
  
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: light
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Topics"
          contents:
            - text: "1: MLK Day - No class"
            - text: "2: History, data, and the digital"
              file: "content/02-content-data-history.qmd"
            - text: "3: The file system and Markdown"
              file: "content/03-content-md.qmd"
            - text: "4: 'Tidy' historical data"
              file: "content/04-content-tidy.qmd"
            - text: "5: Visualizing data with ggplot2"
              file: "content/05-content-ggplot.qmd"
            - text: "6: Wrangling data"
              file: "content/06-content-dplyr.qmd"
            - text: "7: Working with SNiGB"
              file: "content/07-content-snigb.qmd"
            - text: "8: Reproducible workflows with Git"
              file: "content/08-content-git.qmd"
            - text: "9: Making websites with Quarto"
              file: "content/09-content-quarto.qmd"
            - text: "10: Making maps"
              file: "content/10-content-maps.qmd"
            - text: "11: Network analysis"
              file: "content/11-content-networks.qmd"
            - text: "12: Web design and visualization"
              file: "content/12-content-design.qmd"
            - text: "13: Mapping and network analysis"
              file: "content/13-content-gis-sna.qmd"
            - text: "14: Group work on your project"
              file: "content/14-content-build.qmd"
            - text: "15: Presentation of final projects"
              file: "content/15-content-presentations.qmd"

format:
  html:
    theme:
      - cosmo
      - brand
    css: custom.scss
    toc: true



