project:
  type: website

website:
  title: "Digital History Methods"

  announcement:
    icon: calendar-check
    dismissable: true
    content: "This is a **draft** version of the syllabus. The contents will change frequently."
    type: info
    position: below-navbar


  navbar:
    right:
      - href: syllabus.qmd
        text: Syllabus


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



